name: build

on: [push]
    

jobs:

  Build-Libs-Wireguard-Android:
    name: 'Build-Libs-Wireguard-Android'
    if: |
      contains(github.event.head_commit.message, '[all]') ||
      contains(github.event.head_commit.message, '[android]') ||
      contains(github.event.head_commit.message, '[android-wireguard]') ||
      contains(github.event.head_commit.message, '[wireguard]') ||

    steps:
    
    - name: 'Setup Java'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'


    - name: 'Install GO'
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.3

    - name: 'Setup ccache'
      uses: hendrikmuhs/ccache-action@v1.2
          
    - name: 'Get sources'
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 10
        
    - name: 'Get Wireguard'
      uses: actions/checkout@v3
      with:
        repository: WireGuard/wireguard-android
        ref: master
        path: android/wireguard-android       

    - name: 'Build Wireguard binary'
      working-directory: android/wireguard-android
      run: |
        git submodule update --init --recursive
        echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0-rc3"
        ./gradlew assembleRelease        
                

